{% set name = "s2sphere" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/s2sphere-{{ version }}.tar.gz
  sha256: c2478c1ff7c601a59a7151a57b605435897514578fa6bdb8730721c182adbbaf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - future >=0.15

test:
  imports:
    - s2sphere
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sidewalklabs/s2sphere
  summary: Python implementation of the S2 Geometry Library
  license: MIT
  license_file: LICENSE
  doc_url: http://s2sphere.readthedocs.io
  dev_url: https://github.com/sidewalklabs/s2sphere

extra:
  recipe-maintainers:
    - brynpickering
